#
# This applies to all hosts except perfSONAR because it takes care of ntp
#
# Based on steps https://www.certdepot.net/rhel7-set-ntp-service/
# Augmenent with RedHat Docs ntpdate config
#
- hosts: 'bro, dtn'
  become: yes
  become_user: root
  vars_files:
    - site_vars.yaml

  tasks:
    - name: "set timezone to site {{ timezone }}"
      timezone:
         name: "{{ timezone }}"

    - name: install ntp package
      yum: name=ntp state=present

    - name: synchorinze clock
      shell: ntpdate 0.centos.pool.ntp.org 1.centos.pool.ntp.org

    - name: activate ntp service at boot and start it
      service: name=ntpd enabled=yes state=started
