#
# This gets the install log of a machine manually configured
#
#
- hosts: 'bro, dtn'
  become: yes
  become_user: root
  vars_files:
    - site_vars.yaml

  tasks:
    - name: get the anaconda kickstart
      fetch: src=/root/anaconda-ks.cfg dest=install-{{ inventory_hostname }}

    - shell: find /var/log/anaconda -maxdepth 1 -type f
      register: files_to_copy

    - name: fetch the anaconda log dir
      fetch: src={{ item }} dest=install-{{ inventory_hostname }}
      with_items: files_to_copy.stdout_lines

