#
# Configure firewall to support perfSONAR tools
#
# http://www.perfsonar.net/deploy/security-considerations/#Using_perfSONAR_with_Firewalls
#
# Assumes that CentOS7 configures the public zone by default on the host nic
#
# Outbound connections are allowed by default so Outbound restrictions for
# owampd are not implemented
#
- hosts: 'dtn'
  become: yes
  become_user: root
  vars_files:
  - site_vars.yaml


  tasks:
  - name: open inbound control port for one-way ping owampd
    firewalld: port=861/tcp permanent=true state=enabled

  - name: open inbound port range for owampd test channels
    firewalld: port=8760-9960/udp permanent=true state=enabled

  - name: reload firewalld to apply permanent configuration
    shell: firewall-cmd --reload
